apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "member-net-controller-manager.fullname" . }}-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "member-net-controller-manager.labels" . | nindent 4 }}
