run:
  timeout: 15m

linters-settings:
  stylecheck:
    checks: ["all", "-ST1001"]  # Disables dot-import warnings
  revive:
    rules:
      - name: dot-imports
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace