apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "A valid user namespace is required" .Values.userNS }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "A valid system namespace is required" .Values.systemNS }}
