# This pipeline hosted in ADO will use the auto-injected component detection build task to detect possible incidents
# and report alerts related to OSS consumed by this repository.
trigger:
  branches:
    include:
    - main
  paths:  # File paths to include or exclude for triggering a run.
    include:
    - go.sum
    - go.mod

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      echo "This task is used to trigger code base scan."
    displayName: ADO Task
