apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: crp-multi-cluster-app
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: multi-cluster-app
      version: v1
  policy:
    placementType: PickAll
