{{ if .Values.secretTokenForMember.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-member-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
  - watch
  - patch
- apiGroups: 
  - networking.fleet.azure.com
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-member-sa
  namespace: {{ .Values.secretTokenForMember.namespace}}
  labels:
    {{- include "hub-net-controller-manager.labels" . | nindent 4 }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fleet-member-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fleet-member-role
subjects:
  - kind: ServiceAccount
    name: fleet-member-sa
    namespace: {{ .Values.secretTokenForMember.namespace}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretTokenForMember.name}}
  namespace: {{ .Values.secretTokenForMember.namespace}}
  annotations:
    kubernetes.io/service-account.name: fleet-member-sa
type: kubernetes.io/service-account-token
{{ end }}