apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hub-net-controller-manager.fullname" . }}-sa
  namespace: {{ .Values.fleetSystemNamespace }}
  labels:
    {{- include "hub-net-controller-manager.labels" . | nindent 4 }}
