# permissions for end users to view aksclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akscluster-viewer-role
rules:
- apiGroups:
  - networking.aks.io
  resources:
  - aksclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.aks.io
  resources:
  - aksclusters/status
  verbs:
  - get
