# permissions for end users to edit clustersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterset-editor-role
rules:
- apiGroups:
  - networking.aks.io
  resources:
  - clustersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.aks.io
  resources:
  - clustersets/status
  verbs:
  - get
