# permissions for end users to edit serviceexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointsliceexport-editor-role
rules:
- apiGroups:
  - networking.fleet.azure.com
  resources:
  - endpointsliceexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

