# permissions for end users to view internalserviceexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointsliceexport-viewer-role
rules:
- apiGroups:
  - networking.fleet.azure.com
  resources:
  - endpointsliceexports
  verbs:
  - get
  - list
  - watch

