# permissions for end users to edit globalservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalservice-editor-role
rules:
- apiGroups:
  - networking.aks.io
  resources:
  - globalservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.aks.io
  resources:
  - globalservices/status
  verbs:
  - get
