# permissions for end users to view multiclusterservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterservice-viewer-role
rules:
- apiGroups:
  - networking.aks.io
  resources:
  - multiclusterservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.aks.io
  resources:
  - multiclusterservices/status
  verbs:
  - get
