# permissions for end users to edit multiclusterservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterservice-editor-role
rules:
- apiGroups:
  - networking.aks.io
  resources:
  - multiclusterservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.aks.io
  resources:
  - multiclusterservices/status
  verbs:
  - get
