apiVersion: placement.kubernetes-fleet.io/v1alpha1
kind: ResourceOverride
metadata:
  name: ro-nginx-service-export-eastus2euap
  namespace: team-a-nginx
spec:
  placement:
    name: crp-team-a
  resourceSelectors:
    -  group: networking.fleet.azure.com
       kind: ServiceExport
       version: v1alpha1
       name: nginx-service-eastus2euap
  policy:
    overrideRules:
      - clusterSelector:
          clusterSelectorTerms:
            - labelSelector:
                matchExpressions:
                  - key: fleet.azure.com/location
                    operator: NotIn
                    values:
                      - eastus2euap
        overrideType: Delete
#      - clusterSelector:
#          clusterSelectorTerms:
#            - labelSelector:
#                matchLabels:
#                  cluster-name: member-1
#        jsonPatchOverrides:
#          - op: add
#            path: /metadata/annotations
#            value:
#              { "networking.fleet.azure.com/weight": "0" }
#      - clusterSelector:
#          clusterSelectorTerms:
#            - labelSelector:
#                matchLabels:
#                  cluster-name: member-3
#        jsonPatchOverrides:
#          - op: add
#            path: /metadata/annotations
#            value:
#              { "networking.fleet.azure.com/weight": "50" }
#      - clusterSelector:
#          clusterSelectorTerms:
#            - labelSelector:
#                matchLabels:
#                  cluster-name: member-5
#        jsonPatchOverrides:
#          - op: add
#            path: /metadata/annotations
#            value:
#              { "networking.fleet.azure.com/weight": "50" }
