/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "go.goms.io/fleet-networking/api/v1alpha1"
	apiv1alpha1 "go.goms.io/fleet-networking/pkg/applyconfigurations/api/v1alpha1"
	internal "go.goms.io/fleet-networking/pkg/applyconfigurations/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=networking.fleet.azure.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterStatus"):
		return &apiv1alpha1.ClusterStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExportedObjectReference"):
		return &apiv1alpha1.ExportedObjectReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InternalServiceExport"):
		return &apiv1alpha1.InternalServiceExportApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InternalServiceExportSpec"):
		return &apiv1alpha1.InternalServiceExportSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InternalServiceExportStatus"):
		return &apiv1alpha1.InternalServiceExportStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InternalServiceImport"):
		return &apiv1alpha1.InternalServiceImportApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InternalServiceImportSpec"):
		return &apiv1alpha1.InternalServiceImportSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MultiClusterLoadBalancer"):
		return &apiv1alpha1.MultiClusterLoadBalancerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MultiClusterLoadBalancerStatus"):
		return &apiv1alpha1.MultiClusterLoadBalancerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceExport"):
		return &apiv1alpha1.ServiceExportApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceExportStatus"):
		return &apiv1alpha1.ServiceExportStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceImport"):
		return &apiv1alpha1.ServiceImportApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceImportStatus"):
		return &apiv1alpha1.ServiceImportStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServicePort"):
		return &apiv1alpha1.ServicePortApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
