apiVersion: networking.aks.io/v1alpha1
kind: MultiClusterService
metadata:
  name: nginx
  namespace: default
spec:
  clusterSet: clusterset-sample
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP