/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
)

// ExportedObjectReferenceApplyConfiguration represents a declarative configuration of the ExportedObjectReference type for use
// with apply.
type ExportedObjectReferenceApplyConfiguration struct {
	ClusterID       *string    `json:"clusterId,omitempty"`
	APIVersion      *string    `json:"apiVersion,omitempty"`
	Kind            *string    `json:"kind,omitempty"`
	Namespace       *string    `json:"namespace,omitempty"`
	Name            *string    `json:"name,omitempty"`
	ResourceVersion *string    `json:"resourceVersion,omitempty"`
	Generation      *int64     `json:"generation,omitempty"`
	UID             *types.UID `json:"uid,omitempty"`
	NamespacedName  *string    `json:"namespacedName,omitempty"`
	ExportedSince   *v1.Time   `json:"exportedSince,omitempty"`
}

// ExportedObjectReferenceApplyConfiguration constructs a declarative configuration of the ExportedObjectReference type for use with
// apply.
func ExportedObjectReference() *ExportedObjectReferenceApplyConfiguration {
	return &ExportedObjectReferenceApplyConfiguration{}
}

// WithClusterID sets the ClusterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterID field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithClusterID(value string) *ExportedObjectReferenceApplyConfiguration {
	b.ClusterID = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithAPIVersion(value string) *ExportedObjectReferenceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithKind(value string) *ExportedObjectReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithNamespace(value string) *ExportedObjectReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithName(value string) *ExportedObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithResourceVersion(value string) *ExportedObjectReferenceApplyConfiguration {
	b.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithGeneration(value int64) *ExportedObjectReferenceApplyConfiguration {
	b.Generation = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithUID(value types.UID) *ExportedObjectReferenceApplyConfiguration {
	b.UID = &value
	return b
}

// WithNamespacedName sets the NamespacedName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespacedName field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithNamespacedName(value string) *ExportedObjectReferenceApplyConfiguration {
	b.NamespacedName = &value
	return b
}

// WithExportedSince sets the ExportedSince field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExportedSince field is set to the value of the last call.
func (b *ExportedObjectReferenceApplyConfiguration) WithExportedSince(value v1.Time) *ExportedObjectReferenceApplyConfiguration {
	b.ExportedSince = &value
	return b
}
