/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.goms.io/fleet-networking/api/v1alpha1"
	internal "go.goms.io/fleet-networking/pkg/applyconfigurations/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// InternalServiceImportApplyConfiguration represents a declarative configuration of the InternalServiceImport type for use
// with apply.
type InternalServiceImportApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *InternalServiceImportSpecApplyConfiguration `json:"spec,omitempty"`
	Status                           *ServiceImportStatusApplyConfiguration       `json:"status,omitempty"`
}

// InternalServiceImport constructs a declarative configuration of the InternalServiceImport type for use with
// apply.
func InternalServiceImport(name, namespace string) *InternalServiceImportApplyConfiguration {
	b := &InternalServiceImportApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("InternalServiceImport")
	b.WithAPIVersion("networking.fleet.azure.com/v1alpha1")
	return b
}

// ExtractInternalServiceImport extracts the applied configuration owned by fieldManager from
// internalServiceImport. If no managedFields are found in internalServiceImport for fieldManager, a
// InternalServiceImportApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// internalServiceImport must be a unmodified InternalServiceImport API object that was retrieved from the Kubernetes API.
// ExtractInternalServiceImport provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
// Experimental!
func ExtractInternalServiceImport(internalServiceImport *apiv1alpha1.InternalServiceImport, fieldManager string) (*InternalServiceImportApplyConfiguration, error) {
	return extractInternalServiceImport(internalServiceImport, fieldManager, "")
}

// ExtractInternalServiceImportStatus is the same as ExtractInternalServiceImport except
// that it extracts the status subresource applied configuration.
// Experimental!
func ExtractInternalServiceImportStatus(internalServiceImport *apiv1alpha1.InternalServiceImport, fieldManager string) (*InternalServiceImportApplyConfiguration, error) {
	return extractInternalServiceImport(internalServiceImport, fieldManager, "status")
}

func extractInternalServiceImport(internalServiceImport *apiv1alpha1.InternalServiceImport, fieldManager string, subresource string) (*InternalServiceImportApplyConfiguration, error) {
	b := &InternalServiceImportApplyConfiguration{}
	err := managedfields.ExtractInto(internalServiceImport, internal.Parser().Type("io.goms.go.fleet-networking.api.v1alpha1.InternalServiceImport"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(internalServiceImport.Name)
	b.WithNamespace(internalServiceImport.Namespace)

	b.WithKind("InternalServiceImport")
	b.WithAPIVersion("networking.fleet.azure.com/v1alpha1")
	return b, nil
}
func (b InternalServiceImportApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithKind(value string) *InternalServiceImportApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithAPIVersion(value string) *InternalServiceImportApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithName(value string) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithGenerateName(value string) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithNamespace(value string) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithUID(value types.UID) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithResourceVersion(value string) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithGeneration(value int64) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithCreationTimestamp(value metav1.Time) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *InternalServiceImportApplyConfiguration) WithLabels(entries map[string]string) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *InternalServiceImportApplyConfiguration) WithAnnotations(entries map[string]string) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *InternalServiceImportApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *InternalServiceImportApplyConfiguration) WithFinalizers(values ...string) *InternalServiceImportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *InternalServiceImportApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithSpec(value *InternalServiceImportSpecApplyConfiguration) *InternalServiceImportApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *InternalServiceImportApplyConfiguration) WithStatus(value *ServiceImportStatusApplyConfiguration) *InternalServiceImportApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *InternalServiceImportApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *InternalServiceImportApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *InternalServiceImportApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *InternalServiceImportApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
