/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.goms.io/fleet-networking/api/v1alpha1"
	internal "go.goms.io/fleet-networking/pkg/applyconfigurations/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// InternalServiceExportApplyConfiguration represents a declarative configuration of the InternalServiceExport type for use
// with apply.
type InternalServiceExportApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *InternalServiceExportSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *InternalServiceExportStatusApplyConfiguration `json:"status,omitempty"`
}

// InternalServiceExport constructs a declarative configuration of the InternalServiceExport type for use with
// apply.
func InternalServiceExport(name, namespace string) *InternalServiceExportApplyConfiguration {
	b := &InternalServiceExportApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("InternalServiceExport")
	b.WithAPIVersion("networking.fleet.azure.com/v1alpha1")
	return b
}

// ExtractInternalServiceExport extracts the applied configuration owned by fieldManager from
// internalServiceExport. If no managedFields are found in internalServiceExport for fieldManager, a
// InternalServiceExportApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// internalServiceExport must be a unmodified InternalServiceExport API object that was retrieved from the Kubernetes API.
// ExtractInternalServiceExport provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
// Experimental!
func ExtractInternalServiceExport(internalServiceExport *apiv1alpha1.InternalServiceExport, fieldManager string) (*InternalServiceExportApplyConfiguration, error) {
	return extractInternalServiceExport(internalServiceExport, fieldManager, "")
}

// ExtractInternalServiceExportStatus is the same as ExtractInternalServiceExport except
// that it extracts the status subresource applied configuration.
// Experimental!
func ExtractInternalServiceExportStatus(internalServiceExport *apiv1alpha1.InternalServiceExport, fieldManager string) (*InternalServiceExportApplyConfiguration, error) {
	return extractInternalServiceExport(internalServiceExport, fieldManager, "status")
}

func extractInternalServiceExport(internalServiceExport *apiv1alpha1.InternalServiceExport, fieldManager string, subresource string) (*InternalServiceExportApplyConfiguration, error) {
	b := &InternalServiceExportApplyConfiguration{}
	err := managedfields.ExtractInto(internalServiceExport, internal.Parser().Type("io.goms.go.fleet-networking.api.v1alpha1.InternalServiceExport"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(internalServiceExport.Name)
	b.WithNamespace(internalServiceExport.Namespace)

	b.WithKind("InternalServiceExport")
	b.WithAPIVersion("networking.fleet.azure.com/v1alpha1")
	return b, nil
}
func (b InternalServiceExportApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithKind(value string) *InternalServiceExportApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithAPIVersion(value string) *InternalServiceExportApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithName(value string) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithGenerateName(value string) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithNamespace(value string) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithUID(value types.UID) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithResourceVersion(value string) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithGeneration(value int64) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithCreationTimestamp(value metav1.Time) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *InternalServiceExportApplyConfiguration) WithLabels(entries map[string]string) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *InternalServiceExportApplyConfiguration) WithAnnotations(entries map[string]string) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *InternalServiceExportApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *InternalServiceExportApplyConfiguration) WithFinalizers(values ...string) *InternalServiceExportApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *InternalServiceExportApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithSpec(value *InternalServiceExportSpecApplyConfiguration) *InternalServiceExportApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *InternalServiceExportApplyConfiguration) WithStatus(value *InternalServiceExportStatusApplyConfiguration) *InternalServiceExportApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *InternalServiceExportApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *InternalServiceExportApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *InternalServiceExportApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *InternalServiceExportApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
