/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// InternalServiceExportStatusApplyConfiguration represents a declarative configuration of the InternalServiceExportStatus type for use
// with apply.
type InternalServiceExportStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// InternalServiceExportStatusApplyConfiguration constructs a declarative configuration of the InternalServiceExportStatus type for use with
// apply.
func InternalServiceExportStatus() *InternalServiceExportStatusApplyConfiguration {
	return &InternalServiceExportStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *InternalServiceExportStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *InternalServiceExportStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
