/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package v1alpha1

// InternalServiceImportSpecApplyConfiguration represents a declarative configuration of the InternalServiceImportSpec type for use
// with apply.
type InternalServiceImportSpecApplyConfiguration struct {
	ServiceImportReference *ExportedObjectReferenceApplyConfiguration `json:"serviceImportReference,omitempty"`
}

// InternalServiceImportSpecApplyConfiguration constructs a declarative configuration of the InternalServiceImportSpec type for use with
// apply.
func InternalServiceImportSpec() *InternalServiceImportSpecApplyConfiguration {
	return &InternalServiceImportSpecApplyConfiguration{}
}

// WithServiceImportReference sets the ServiceImportReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceImportReference field is set to the value of the last call.
func (b *InternalServiceImportSpecApplyConfiguration) WithServiceImportReference(value *ExportedObjectReferenceApplyConfiguration) *InternalServiceImportSpecApplyConfiguration {
	b.ServiceImportReference = value
	return b
}
