/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// InternalServiceExportSpecApplyConfiguration represents a declarative configuration of the InternalServiceExportSpec type for use
// with apply.
type InternalServiceExportSpecApplyConfiguration struct {
	Ports                  []ServicePortApplyConfiguration            `json:"ports,omitempty"`
	ServiceReference       *ExportedObjectReferenceApplyConfiguration `json:"serviceReference,omitempty"`
	Type                   *v1.ServiceType                            `json:"type,omitempty"`
	IsDNSLabelConfigured   *bool                                      `json:"isDNSLabelConfigured,omitempty"`
	IsInternalLoadBalancer *bool                                      `json:"isInternalLoadBalancer,omitempty"`
	PublicIPResourceID     *string                                    `json:"publicIPResourceID,omitempty"`
	Weight                 *int64                                     `json:"weight,omitempty"`
}

// InternalServiceExportSpecApplyConfiguration constructs a declarative configuration of the InternalServiceExportSpec type for use with
// apply.
func InternalServiceExportSpec() *InternalServiceExportSpecApplyConfiguration {
	return &InternalServiceExportSpecApplyConfiguration{}
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *InternalServiceExportSpecApplyConfiguration) WithPorts(values ...*ServicePortApplyConfiguration) *InternalServiceExportSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPorts")
		}
		b.Ports = append(b.Ports, *values[i])
	}
	return b
}

// WithServiceReference sets the ServiceReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceReference field is set to the value of the last call.
func (b *InternalServiceExportSpecApplyConfiguration) WithServiceReference(value *ExportedObjectReferenceApplyConfiguration) *InternalServiceExportSpecApplyConfiguration {
	b.ServiceReference = value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *InternalServiceExportSpecApplyConfiguration) WithType(value v1.ServiceType) *InternalServiceExportSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithIsDNSLabelConfigured sets the IsDNSLabelConfigured field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsDNSLabelConfigured field is set to the value of the last call.
func (b *InternalServiceExportSpecApplyConfiguration) WithIsDNSLabelConfigured(value bool) *InternalServiceExportSpecApplyConfiguration {
	b.IsDNSLabelConfigured = &value
	return b
}

// WithIsInternalLoadBalancer sets the IsInternalLoadBalancer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsInternalLoadBalancer field is set to the value of the last call.
func (b *InternalServiceExportSpecApplyConfiguration) WithIsInternalLoadBalancer(value bool) *InternalServiceExportSpecApplyConfiguration {
	b.IsInternalLoadBalancer = &value
	return b
}

// WithPublicIPResourceID sets the PublicIPResourceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicIPResourceID field is set to the value of the last call.
func (b *InternalServiceExportSpecApplyConfiguration) WithPublicIPResourceID(value string) *InternalServiceExportSpecApplyConfiguration {
	b.PublicIPResourceID = &value
	return b
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *InternalServiceExportSpecApplyConfiguration) WithWeight(value int64) *InternalServiceExportSpecApplyConfiguration {
	b.Weight = &value
	return b
}
