/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MultiClusterLoadBalancerStatusApplyConfiguration represents a declarative configuration of the MultiClusterLoadBalancerStatus type for use
// with apply.
type MultiClusterLoadBalancerStatusApplyConfiguration struct {
	LoadBalancer *v1.LoadBalancerStatus               `json:"loadBalancer,omitempty"`
	Conditions   []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MultiClusterLoadBalancerStatusApplyConfiguration constructs a declarative configuration of the MultiClusterLoadBalancerStatus type for use with
// apply.
func MultiClusterLoadBalancerStatus() *MultiClusterLoadBalancerStatusApplyConfiguration {
	return &MultiClusterLoadBalancerStatusApplyConfiguration{}
}

// WithLoadBalancer sets the LoadBalancer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancer field is set to the value of the last call.
func (b *MultiClusterLoadBalancerStatusApplyConfiguration) WithLoadBalancer(value v1.LoadBalancerStatus) *MultiClusterLoadBalancerStatusApplyConfiguration {
	b.LoadBalancer = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MultiClusterLoadBalancerStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *MultiClusterLoadBalancerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
