/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/
// Code generated by applyconfiguration-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "go.goms.io/fleet-networking/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// ServiceImportStatusApplyConfiguration represents a declarative configuration of the ServiceImportStatus type for use
// with apply.
type ServiceImportStatusApplyConfiguration struct {
	IPs                   []string                          `json:"ips,omitempty"`
	Type                  *apiv1alpha1.ServiceImportType    `json:"type,omitempty"`
	SessionAffinity       *v1.ServiceAffinity               `json:"sessionAffinity,omitempty"`
	SessionAffinityConfig *v1.SessionAffinityConfig         `json:"sessionAffinityConfig,omitempty"`
	Ports                 []ServicePortApplyConfiguration   `json:"ports,omitempty"`
	Clusters              []ClusterStatusApplyConfiguration `json:"clusters,omitempty"`
}

// ServiceImportStatusApplyConfiguration constructs a declarative configuration of the ServiceImportStatus type for use with
// apply.
func ServiceImportStatus() *ServiceImportStatusApplyConfiguration {
	return &ServiceImportStatusApplyConfiguration{}
}

// WithIPs adds the given value to the IPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPs field.
func (b *ServiceImportStatusApplyConfiguration) WithIPs(values ...string) *ServiceImportStatusApplyConfiguration {
	for i := range values {
		b.IPs = append(b.IPs, values[i])
	}
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ServiceImportStatusApplyConfiguration) WithType(value apiv1alpha1.ServiceImportType) *ServiceImportStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithSessionAffinity sets the SessionAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionAffinity field is set to the value of the last call.
func (b *ServiceImportStatusApplyConfiguration) WithSessionAffinity(value v1.ServiceAffinity) *ServiceImportStatusApplyConfiguration {
	b.SessionAffinity = &value
	return b
}

// WithSessionAffinityConfig sets the SessionAffinityConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionAffinityConfig field is set to the value of the last call.
func (b *ServiceImportStatusApplyConfiguration) WithSessionAffinityConfig(value v1.SessionAffinityConfig) *ServiceImportStatusApplyConfiguration {
	b.SessionAffinityConfig = &value
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *ServiceImportStatusApplyConfiguration) WithPorts(values ...*ServicePortApplyConfiguration) *ServiceImportStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPorts")
		}
		b.Ports = append(b.Ports, *values[i])
	}
	return b
}

// WithClusters adds the given value to the Clusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Clusters field.
func (b *ServiceImportStatusApplyConfiguration) WithClusters(values ...*ClusterStatusApplyConfiguration) *ServiceImportStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithClusters")
		}
		b.Clusters = append(b.Clusters, *values[i])
	}
	return b
}
