apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
spec:
  selector:
    app: nginx
    index: "{{.Index}}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
