---
{{- if not .Values.userNS -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.userNS }}
{{- end -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "A valid system namespace is required" .Values.systemNS }}
---
{{- range .Values.memberClusterConfigs -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: fleet-member-{{ required "A valid member ID is required" .memberID }}
---
{{- end -}}
