name: Prune GHCR Dev Images

on:
  # push:
  workflow_dispatch:
  schedule:
    # Every Monday at 09:00 (9:00 AM)
    - cron:  '0 9 * * 1'
  pull_request:
    branches:
      - main

env:
  HUB_NET_CONTROLLER_MANAGER_IMAGE_NAME : dev/hub-net-controller-manager
  MEMBER_NET_CONTROLLER_MANAGER_IMAGE_NAME: dev/member-net-controller-manager
  MCS_CONTROLLER_MANAGER_IMAGE_NAME: dev/mcs-controller-manager

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Prune untagged default
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ env.GITHUB_REPOSITORY_OWNER }}
          container: ${{ env.HUB_NET_CONTROLLER_MANAGER_IMAGE_NAME }}
          dry-run: true
          older-than: 1 # days